server:
  port: 8888
  address: 13.53.193.215   # Bind to all network interfaces, including the EC2 IPv4

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Pransquare/CloudConfig.git
          clone-on-start: true
